apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: python
      image: python:3.12-slim
      command: ["sleep"]
      args: ["99d"]
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command: ["sleep"]
      args: ["99d"]
      volumeMounts:
        - name: registry-credentials
          mountPath: /kaniko/.docker
    - name: kubectl
      image: alpine/k8s:1.29.0
      command: ["sleep"]
      args: ["99d"]
  volumes:
    - name: registry-credentials
      secret:
        secretName: registry-credentials
